version: "3.8"
   
services:
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python SpiritFire/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - "./SpiritFire/db.sqlite3:/code/SpiritFire/db.sqlite3"
    ports:
      - "8000:8000"
    # depends_on:
    #   - db